spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=admin
spring.datasource.password=password
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.openai.api-key=
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-completion-tokens=1024